/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CookieButton: typeof import('./src/components/cookie-button/CookieButton.vue')['default']
    CookieCalendar: typeof import('./src/components/cookie-date-picker/cookieCalendar.vue')['default']
    CookieCard: typeof import('./src/components/cookie-card/CookieCard.vue')['default']
    CookieCountdown: typeof import('./src/components/cookie-countdown/CookieCountdown.vue')['default']
    CookieCountDown: typeof import('./src/components/cookie-countdown/CookieCountDown.vue')['default']
    CookieDatePicker: typeof import('./src/components/cookie-date-picker/CookieDatePicker.vue')['default']
    CookieDialog: typeof import('./src/components/cookie-dialog/CookieDialog.vue')['default']
    CookieEmpty: typeof import('./src/components/CookieEmpty/CookieEmpty.vue')['default']
    CookieForm: typeof import('./src/components/cookie-form/CookieForm.vue')['default']
    CookieFormItem: typeof import('./src/components/cookie-form/CookieFormItem.vue')['default']
    CookieInput: typeof import('./src/components/cookie-input/CookieInput.vue')['default']
    CookieLoading: typeof import('./src/components/cookie-loading/CookieLoading.vue')['default']
    CookieLogin: typeof import('./src/components/CookieLogin.vue')['default']
    CookieMenu: typeof import('./src/components/cookie-menu/CookieMenu.vue')['default']
    CookieMenuItem: typeof import('./src/components/cookie-menu/CookieMenuItem.vue')['default']
    CookieOption: typeof import('./src/components/cookie-select/CookieOption.vue')['default']
    CookieRadio: typeof import('./src/components/cookie-radio/CookieRadio.vue')['default']
    CookieRadioGroup: typeof import('./src/components/cookie-radio/CookieRadioGroup.vue')['default']
    CookieSelect: typeof import('./src/components/cookie-select/CookieSelect.vue')['default']
    CookieSubMenu: typeof import('./src/components/cookie-menu/CookieSubMenu.vue')['default']
    CookieTime: typeof import('./src/components/cookie-time-picker/CookieTime.vue')['default']
    CookieTimePicker: typeof import('./src/components/cookie-time-picker/CookieTimePicker.vue')['default']
    CookieTimeSelect: typeof import('./src/components/cookie-time-picker/CookieTimeSelect.vue')['default']
    CookieUpload: typeof import('./src/components/cookie-upload/CookieUpload.vue')['default']
    DiscussHottest: typeof import('./src/components/discuss/DiscussHottest.vue')['default']
    DiscussNewest: typeof import('./src/components/discuss/DiscussNewest.vue')['default']
    DiscussRecommend: typeof import('./src/components/discuss/DiscussRecommend.vue')['default']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    MenuBar: typeof import('./src/components/TipTap/MenuBar.vue')['default']
    MenuItem: typeof import('./src/components/TipTap/MenuItem.vue')['default']
    Preview: typeof import('./src/components/TipTap/preview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('./src/components/swiper/Swiper.vue')['default']
    TeamInfo: typeof import('./src/components/TeamInfo.vue')['default']
    TipTap: typeof import('./src/components/TipTap/TipTap.vue')['default']
  }
}
